before_install: echo "MAVEN_OPTS='-Xmx3072m'" > ~/.mavenrc
sudo: required
install: true
language: java
addons:
  sonarcloud:
    organization: maxdemarzi-github
    token:
      secure: Lft6ATDvbfenCK/wdf3h6y4VdTjvCWCHyd3W3OQn7KxyCcgPRQt31qEmx/RoplO/yAfD0FNwEAXPdJaALEDMgn3t82xA5L8W+jYObRlbX81gC4Zc+c58Gm0Oe49AxFfmotp0fBCL3NLkiOX3DoCThytTpfprfxpcALXpDjRifmlYQtoi8OLpDjcsHM2842iUwTBKEeFP/AxBcdGWlOO66YiEYIhKwKq+fH5cJNMYTH2tEI3fuvYkwoN+f5ZeaZzMgJoH0Oz3HUoNXe+5q6UZJ6jqJe1bkemN++AjeiP/xFiwog8UYp6Y0I9EDp8BaqF5wHgIWedRbbbj/pQYRfkANBLu0Z+yQ8xeZ+kc943Z3KJOp3gpHLKhqWZlY+YYlNpq8d4SCCIymcTANiYKxWgvcv6NNg7DfLA08UUjVR5FpckpVxAKRLspn/P04WITX3MZeLsGjqN/KmFE2J1rKA56bPwFdA+NymS5/e3kLbOKyziu3uKbd7g5j/8y8uYR6sU3E7JUQXJruqelW2cVT6SnLo0LAXbNekH8S972EJYLYqPsy3iotO/jLwhioiOAtOfhogxNMVNbnR074cN+09+Jpi5Qw2aA3kKmTUfZmkxWwV5SxmfdAvnJdKryES10dgV13Yir6MT7G+G2zyuvctYCKPbh2jAq+1zha732Gql0EGk=
    github_token:
      secure: ptBcyyvROFA+/5awKAM4rXQqMECKYkNDgECPHBZAEpyuF0WC6BqfG9FaqVHIAGD0PgNzmgHaLsyPyhuWiue2ErHmKyUE6cmEz7AFAynITbVzbyGPZo6dgVitXinJzTEJaiopeB7KELd2OeQVxE82U53hAnX9olcrDM5gprn8tokRTG8TkRRMuY/L3yaObpzZ7Zy7ldoytF5SNsWK9W8SLbVDvBDi5B1rxE7cr0e8QTT4yf8cerDzusADcAbALuTnyAFkAdY35HVQ3crBTU0xkB1y/2GEfZowN1wb2G4N7bKiOgXxFPt9jIFUSpsHnYlGp6Wtc/ZdtDaoMUw/kGfshcdx93ktD5ERxZwMtasU4ABJIcrphzZC7hfy6eQ9AOYdYVgOwIrB05JWje1uO/sCzq6eeah3rLSFy74JAyomSykbiGUA2gbi34UsRWrQMrxqXWAToRt9ZGbo/BpFY56tk3CA2FvI/28j6XZuxk5YIOfNgCr6d1XxhdKJbaznD+KX80VZmGyNsyyQc0sjd3T4tl5OJqoIFOPzieMnTFk2fTxN/I2GURx3Xmjw8k5jaVTGtgATttYUJ+2MvPHkRKGbyxPmR5kwq9fS94GFA41XZQ81V4MeEdX72e2C31Kp651anUzwe3bTFPliSwKQVUpWGWNUeU5jMCIYtgBel6SI6Bs=
jdk:
- oraclejdk8
script:
- mvn test -B -q
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: vj/q1Z7lBrqzEMZSwCpr6YgxlUnSFVuhAv1hxMFltRiSaa5flJJPI0VY+htKlqHr8PcGlWRatr4njxIj8WvZOGP3RoyUMOaA/9TNaa3qFIXx8G6FitdsDBZGvsK10ISTRksAubI0qkOOaDUfcVzTI0uTgJbmuIqD8fV2WWPgZasdyzVORYsHAV7hGjQ1SAzlPzm/pDKOs9eRUDe1xwEDx3MX0SVDeUv+CRHIobxh8HUOc9e9GVeNK+u+q1DvRJwCzr/eDLrKPBx9N5hL9SOfq9niWIQu/M6Juc74OF/ujI5qzBRLZV/2WgQkE4SVJ1Irj+wqWRTP7BoDH6WAMHFx1jj0yuc2CjS6su8YwwCfcMJ+nxOwUBG887Oslwh+w+xp1EH9OYG1sO0A8CyrNeVp8zva2f5tkLTDQ+8jyj38lYwVTwKUg3Rx1ySwkdafFIlT2eVROoA6BLxzTweoCGB/wAokSdJmcY+rzqzHFPLYfosTGa3bFtkQCIGcmfPromprh9ZAb0dt/bnzHzLnE6uL+9BXT9NIxn//KAvJpsQ118fcssk4TZnyNWzoN/iUnbhO78+1myeGctm4kQeBdMLDrJndwSM0kUD7+QcnHZ6P9SziaBxjnr7VEzBJLcLnDwqbW6Z9O1a0CI2AjU/6vnvDEeoJMisE1JKYd3yLZVX2oi4=
  - secure: tw73i55bCqDFt8Rn58o0P53RvnDrjnGnmtvpnA7MoJbLtZ1EIkCXfyPIHRT3hZD9Lfjdv6xLI9dUO3Efb7PNjzoVh5OL9323udlNxJNXwvAOb2cyyOuSr43jO/rjdWAb80iJ1XGehPG33vUVbNqbIJRP3gb8Yz9VpJGJ0xPp8/6P8QM86f7lS0zm9yqJ/H2EzeZjiL2MDBtmpH7K/nUEg568PBU+dhTvU/2lBoaU+rtTndza2n5ECbkTrTie5WUmlg7icBHMGRf2yF8I6nsvAj3/gWaxD9HnoEknEcZvfEv679lkse098AlOEjC+4OG0SrLHD4ztGXmv1AS1V3YfEjbEjGElHH9CTwrlcd40T9GY8AoAmdo7A0LtDd5Nenhn6EFWJU4xEBDDvWHE4yOgp/cufOyhai674M39IyznN2/JXvlfIfyOtSFvq73Ut270u86EpYJIfHFUFAQHNmb1Q5XipjNU9hTsnn1ruXNlx8I5IunE0Q13l+8mlMCltomG8qBeDBHtuGaELmeC7rqofZswwSfP4bOAdV5Xc80yTNj1kgspj/pnHXKshTtoYL3DiQNE+FrvYKoc+2tklOHz0mt3U9dky0EpP7vPmRTTQEZivJ2tf89wvw1p6B3479OaB5MQ7rQHVF4dvXn8OaQQaqcglrzLkpVk5OcUf5LqTmg=
after_success:
- mvn test jacoco:report coveralls:report
- sonar-scanner
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- export REPO=maxdemarzi/pebbledb
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
