package com.pebbledb.actions;

public enum Action {
    GET_NODE, POST_NODE, DELETE_NODE,
    PUT_NODE_PROPERTIES, DELETE_NODE_PROPERTIES,
    GET_NODE_PROPERTY, PUT_NODE_PROPERTY, DELETE_NODE_PROPERTY,
}
